name: Calling another workflow from alamzia23/hello-world

on:
  push:
    branches:
      - main

jobs:
  my-job:
    uses: alamzia23/hello-world/.github/workflows/main.yml@main
    steps:
      - name: Install dependencies
        run: npm install @actions/github
