name: Calling another workflow from alamzia23/hello-world

on:
  push:
    branches:
      - main

jobs:
  my-job:
    steps:
      - name: Install dependencies  # New step to install the package
        run: npm install @actions/github

      - name: Calling another workflow
        uses: alamzia23/hello-world/.github/workflows/main.yml@main
