name: Calling another workflow in alamzia23/hello-world

on:
  push:
    branches: [ main ]

jobs:
  call-other-workflow:
    runs-on: ubuntu-latest
    uses: alamzia23/hello-world/.github/workflows/main.yml@main

