name: Calling another workflow from alamzia23/hello-world

on:
  push:
    branches:
      - main

jobs:
  my-job:
    uses: alamzia23/hello-world/.github/workflows/main.yml@main  # Correct placement
    with:
        repo-token: ${{ secrets.TOKEN_KEY }}
  
