name: Calling another workflow from alamzia23/hello-world

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install @actions/github
      

  my-job:
    needs: install-dependencies
    uses: alamzia23/hello-world/.github/workflows/main.yml@main






