name: Calling another workflow in alamzia23/hello-world

on:
  push:
    branches: [ main ]

jobs:
  call-other-workflow:
    runs-on: ubuntu-latest
    uses: .github/workflows/main.yml@main # Move the `uses` here

    steps:
      - uses: actions/checkout@v3 # Other steps remain within the `steps` section

