name: Tested Comment Checker for Merged PRs


on:
  push:
  workflow_call:

jobs:
  check_merged_pr_comments:
    runs-on: ubuntu-latest

    permissions:
      issues: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18  # Your preferred Node.js version
      - run: npm install @actions/core @octokit/rest  # Install dependencies

      - name: Check for tested comments in merged PRs
        id: check_comments
        run: |
          node ./actions/ListofPRs/index.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_KEY }}

      - name: Process filtered comments
        if: steps.check_comments.outputs.filtered_comments
        run: |
          echo "Found ${{ steps.check_comments.outputs.filtered_comments.length }} comments containing 'TESTED' in merged PR:"
          for comment in ${{ steps.check_comments.outputs.filtered_comments }}; do
            echo "- ${comment.body}"
          done
