name: Calling another workflow from alamzia23/hello-world

on:
  push:
    branches:
      - main

jobs:
   my-job:
     steps:
       - uses: alamzia23/hello-world/.github/workflows/mail.yml@main  


